name: Website Build and Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.WWW_IP }}
          port: ${{ secrets.WWW_SSH_PORT }}
          username: ${{ secrets.WWW_SSH_USERNAME }}
          password: ${{ secrets.WWW_SSH_PASSWORD }}
          local_path: './public/*'
          remote_path: '/home/hdrmaa-www/htdocs/www.hendraa.my.id'
          sftp_only: true
